using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRsystem.Api.Database.DataTables
{

    [Table("Tb_Employee_Devices")]
    public class TbEmployeeDevices
    {
        [Key]

        public int DeviceId { get; set; }

        [Required]
        public int EmployeeId { get; set; }

        /// <summary>
        /// The persistent UUID generated by the app and stored in Secure Storage.
        /// </summary>
        [Required]
        [StringLength(100)]
        public string DeviceUuid { get; set; } = string.Empty;

        /// <summary>
        /// The native OS ID (androidId or identifierForVendor).
        /// </summary>
        [StringLength(255)]
        public string? NativeOsId { get; set; }

        [StringLength(100)]
        public string? ModelName { get; set; }

        [Required]
        [StringLength(20)]
        public string OsType { get; set; } = string.Empty; // e.g., "Android" or "iOS"

        [StringLength(20)]
        public string? OsVersion { get; set; }

        [StringLength(100)]
        public string? Manufacturer { get; set; }

        [Required]
        public bool IsPhysical { get; set; } = true;

        /// <summary>
        /// Set to DateTime(6) precision in MySql.
        /// We handle the value in C# code.
        /// </summary>
        [Required]
        public DateTime RegisteredAt { get; set; } = DateTime.UtcNow;

        [Required]
        public DateTime LastActiveAt { get; set; } = DateTime.UtcNow;


        [Required]
        public bool IsActiveDevice { get; set; } = true;


        public int? ResetByUserId { get; set; }

        public DateTime? ResetByUserDate { get; set; } =  DateTime.UtcNow;






    }
}

